### ISSUE TITLE
Loading of the CSS file

### ISSUE THREAD

**Issue by moikorg** [rschmehl/reveal-plugins#1]
Hi
I think for the description in the README.md there is a little mistake. 

Loading of the CSS should be done like this:
`<link rel="stylesheet" href="dist/attribution.css">`

and not with loading the `plugin.js` file, isn't it?

Thanks for the cool plugin

**Comment by rschmehl** [comment]
Hi @moikorg,
Well spotted, yes, the plugin's css-stylesheet should be loaded here, of course.
